name: Deploy to Live Server (FTP - Reliable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to FTP (Reliable Mode)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/learn/
        dangerous-clean-slate: false
        timeout: 900000
        max-retries: 5
        log-level: verbose
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/config.php
          **/moodledata/**
          **/*.log
          **/*.sql
          **/*.sqlite
          **/temp/**
          **/cache/**
          **/vendor/**
          **/.DS_Store
          **/*.tmp
          **/*.bak
          **/deploy.config*
          **/DEPLOYMENT.md
          **/scripts/**
          **/custom-configs/**
          **/user-uploads/**
          **/local-modifications/**
          **/lib/phpspreadsheet/**
          **/lib/tcpdf/**
          **/lib/yui/**
          **/lib/pear/**
          **/lib/phpmailer/**
          **/lib/plist/**
          **/lib/ralouphie/**
          **/lib/userkey/**
          **/lib/xmldb/**
          **/lib/xhtml.xsl**
          **/lib/searchlib.php**
          **/lib/requirejs.php** 